dist: trusty
language: node_js
node_js:
  - "8"
addons:
  chrome: stable
install:
  - yarn install
before_script:
  - export chrome=google-chrome-stable
  - export chromium=google-chrome-stable
script:
  - yarn run build
  - yarn run spec-node
  - yarn run spec-web
cache:
  yarn: true
  directories:
    - "node_modules"