version: '2.4'
services:
  streaming-service:
    image: d8s/streaming-service
    container_name: streaming-service
    ports:
      - "5801:5801"
    networks:
      - d8s-network
    build:
      context: .
      dockerfile: ./src/streaming-service/dockerfile
    cpus: 0.5
    mem_limit: 512m
    mem_swappiness: 0
    restart: on-failure
networks:
  d8s-network: